package com.app;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_ENTITY.
 */
public class UserEntity {

    private Long id;
    /** Not-null value. */
    private String email;
    /** Not-null value. */
    private String pw;
    /** Not-null value. */
    private String nickname;
    private int isLogin;

    public UserEntity() {
    }

    public UserEntity(Long id) {
        this.id = id;
    }

    public UserEntity(Long id, String email, String pw, String nickname, int isLogin) {
        this.id = id;
        this.email = email;
        this.pw = pw;
        this.nickname = nickname;
        this.isLogin = isLogin;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getEmail() {
        return email;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmail(String email) {
        this.email = email;
    }

    /** Not-null value. */
    public String getPw() {
        return pw;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPw(String pw) {
        this.pw = pw;
    }

    /** Not-null value. */
    public String getNickname() {
        return nickname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public int getIsLogin() {
        return isLogin;
    }

    public void setIsLogin(int isLogin) {
        this.isLogin = isLogin;
    }

}
